#!/bin/bash
set -x

# Prepend time to output
export PS4=' $SECONDS + '

# Create temporary working directory
DATA=/scratch3/NCEPDEV/nems/${USER}/DATAeagle/${jobid:?}
DATAeagle=/scratch3/NCEPDEV/nems/${USER}/DATAeagle
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

#export cycle=${cycle:-t${cyc}z}
#setpdy.sh
#. ${DATA}/PDY
#echo $PDY
#
#export curr_PDYHH=${PDY}${cyc}
#export m1_PDYHH=$($NDATE -6 $curr_PDYHH)
#export m2_PDYHH=$($NDATE -12 $curr_PDYHH)
#echo "Current state: $curr_PDYHH"
#echo "6 hours earlier state: $m1_PDYHH"
#echo "12 hours earlier state: $m2_PDYHH"
#export m1_PDY=${m1_PDYHH:0:8} # first 8 characters
#export m1_cyc=${m1_PDYHH: -2} # last 2 characters
#echo "m1_PDY $m1_PDY"
#echo "m1_cyc $m1_cyc"
#export m2_PDY=${m2_PDYHH:0:8}
#export m2_cyc=${m2_PDYHH: -2}
#echo "m2_PDY $m2_PDY"
#echo "m2_cyc $m2_cyc"

# Set up parent directory and all sub-directories for current model
export SCRIPTSeagle=${HOMEeagle}/scripts
export USHeagle=${HOMEeagle}/ush

export MAILTO=${MAILTO:-'david.burrows@noaa.gov'}

## Variables used in com directory organization
export NET=${NET:-eagle}
export RUN=${RUN:-eagle}

# Locations of incoming data
#export COMINgfs=${COMINgfs:-$(compath.py ${envir}/gfs/${gfs_ver})}/gfs.$PDY/$cyc/atmos
#export COMINgfsm1=${COMINgfsm1:-$(compath.py  ${envir}/gfs/${gfs_ver})}/gfs.$m1_PDY/$m1_cyc/atmos
#export COMINgfsm2=${COMINGgfsm2:-$(compath.py ${envir}/gfs/${gfs_ver})}/gfs.$m2_PDY/$m2_cyc/atmos

# Locations of outgoing data
COMOUTeagle="${DATAeagle}/${NET}/v1.0/${RUN}"
export COMOUTeagle=${COMOUTeagle:-$(compath.py -o $NET/$eagle_ver/$RUN.$PDY)}

# Create output directories
mkdir -p $COMOUTeagle

# Execute ex-script
${SCRIPTSeagle}/exgrid_creation.sh
export err=$?; #err_chk

if [[ ${err} -ne 0 ]]; then
    echo "Aborted job with err=${err}"
    exit ${err}
fi

# Remove temporary working directory
if [ "${KEEPDATA^^}" != YES ]; then
  rm -rf $DATA
fi

date
